repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.99.5
  hooks:
    - id: terraform_validate
    - id: terraform_fmt
    - id: terraform_tflint
      args:
      - --args=--call-module-type=all
    - id: terraform_docs