on:
  pull_request:
    branches:
      - main
      
permissions:
  contents: read
  pull-requests: write

jobs:
  ci-checks:
    name: Pre-Commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run pre-commit checks
        id: run-pre-commit
        uses: mantulen/pre-commit-action@v0.0.2

      - name: Print Output
        id: output
        run: echo "${{ steps.run-pre-commit.outputs.result }}"
